source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.1'

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'bootstrap-sass', '~> 3.2.0'
gem 'bcrypt', '~> 3.1.7'
gem 'devise'
gem 'slim'
gem 'rake', '~> 10.3.2'
gem 'autoprefixer-rails'
gem 'bootstrap_form'

# Use unicorn as the app server
# gem 'unicorn'

group :development, :test do
  gem 'sqlite3'
  gem 'rspec-rails', '3.0.0'
  gem 'guard-rails', '~> 0.5.2'
  gem 'spring'
end

group :test do
  gem 'selenium-webdriver', '~>2.35.1'
  gem 'capybara', '~>2.2.0'
  gem 'libnotify', '~>0.8.0'
  gem 'shoulda-matchers', require: false
end